CrazyBooks/CrazyBooks/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrazyBooks.Models
{
  public class Book
  {

    public int Id { get; set; }

    public string Title { get; set; }

    public string ISBN { get; set; }
   
  }
}

CrazyBooks/CrazyBooks/Models/ErrorViewModel.cs
namespace CrazyBooks.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrazyBooks/CrazyBooks/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrazyBooks.Models
{
  public class Subject
  {
    
    public int Id { get; set; }

    public string Name { get; set; }

  }
}

CrazyBooks/CrazyBooks/Controllers/BookController.cs
using CrazyBooks.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrazyBooks.Controllers
{
  public class BookController : Controller
  {
    public IActionResult Index()
    {
      this.ViewBag.MaListe = new List<Book>()
      {
        new Book(){ Id=1, Title= "Cobayes", ISBN= "9782896623921"},
        new Book(){Id=2, Title= "Enlèvement", ISBN= "9782896626151" },
        new Book(){Id=3, Title= "Le chiffreur", ISBN= "9782890747364" },
        new Book(){Id=4, Title= "Les Maudits", ISBN= "9782896628773"}
      };
      return View();
    }

    //GET CREATE
    public IActionResult Create()
    {
      return View();
    }

    //POST CREATE
    [HttpPost]
    public IActionResult Create(Book book)
    {
      if (ModelState.IsValid)
      {
        // Ajouter à la BD
      }

      return this.View(book);
    }
  }
}

CrazyBooks/CrazyBooks/Controllers/HomeController.cs
using CrazyBooks.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrazyBooks.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CrazyBooks/CrazyBooks/Controllers/SubjectController.cs
using CrazyBooks.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CrazyBooks.Controllers
{
  public class SubjectController : Controller
  {
    public IActionResult Index()
    {
      this.ViewBag.MaListe = new List<Subject>()
      {
        new Subject(){Name= "Thriller", Id=1},
        new Subject(){Name= "Biographie", Id=2},
        new Subject(){Name= "Drame", Id=3},
        new Subject(){Name= "Ressources humaines", Id=4}
      };
      return View();
    }

    //GET CREATE
    public IActionResult Create()
    {
      return View();
    }

    //POST CREATE
    [HttpPost]
    public IActionResult Create(Subject subject)
    {
      if (ModelState.IsValid)
      {
        // Ajouter à la BD
      }

      return this.View(subject);
    }
  }
}

CrazyBooks/CrazyBooks/Views/Book/Create.cshtml
@model CrazyBooks.Models.Book
<div class="border p-3 DivBgForm text-light">
    <form class="form-horizontal" method="post" asp-action="Create">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h1 class="text-primary pl-3">Create a Book</h1>
            <hr />
        </div>

        <div class="col-8  pt-4">
            <div class="form-group row p-2">
                <div class="col-2">
                    <label asp-for="@Model.Title"></label>
                </div>
                <div class="col-8">
                    <input asp-for="@Model.Title" class="form-control" />
                    <span asp-validation-for="@Model.Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-2">
                <div class="col-2">
                    <label asp-for="@Model.ISBN"></label>
                </div>
                <div class="col-8">
                    <input asp-for="@Model.ISBN" class="form-control" />
                    <span asp-validation-for="@Model.ISBN" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row p-2">
                <div class="col-8 offset-2 row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100" value="Create" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-100">Back to list</a>
                    </div>
                </div>
            </div>

        </div>
    </form>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
  }

CrazyBooks/CrazyBooks/Views/Book/Index.cshtml
<div class="container p-3 DivBgForm text-light" >
  <div class="row pt-4">
    <div class="col-10">
      <h1 class="text-primary">Books</h1>
    </div>
    <div class="col-2 text-right">
      <a asp-controller="Book" asp-action="Create" class="btn btn-success">
        Create New Subject
      </a>
    </div>
  </div>

  <br /><br />
    <table class="table table-bordered border-dark text-light" style="width:100%">
    <thead class="bg-primary">
      <tr>
        <th>Title</th>
        <th>ISBN</th>
        <th></th>
      </tr>
    </thead>
    <tbody class="border-dark">
      @foreach (var item in this.ViewBag.MaListe)
      {
        <tr>
          <td width="50%">@item.Title</td>
          <td width="20%">@item.ISBN</td>
          <td class="text-center">
            <div class="w-75 btn-group" role="group">
              <a class="btn btn-warning mx-2">
                Edit
              </a>
              <a class="btn btn-danger mx-2">
                Delete
              </a>
            </div>
          </td>
        </tr>
      }

    </tbody>
  </table>
</div>

CrazyBooks/CrazyBooks/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CrazyBooks/CrazyBooks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrazyBooks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/images/imagesLayout/tile.png" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Administration
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" asp-controller="Subject" asp-action="Index">Manage Subjects</a></li>
                <li><a class="dropdown-item" asp-controller="Book" asp-action="Index">Manage Books</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-dark bg-light">
    <div class="container">
      &copy; 2021 - CrazyBooks - Valérie Turgeon <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CrazyBooks/CrazyBooks/Views/Subject/Create.cshtml
@model CrazyBooks.Models.Subject

<form method="post" asp-action="Create">
    <div class="border p-3 DivBgForm text-light">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
      <h1 class="text-primary pl-3">Create a Subject</h1>
      <hr />
    </div>

    <div class="row">
      <div class="col-8">
        <div class="form-group row">
          <div class="col-2">
            <label asp-for="Name"></label>
          </div>
          <div class="col-8">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
          </div>
        </div>

        <div class="form-group row py-2">
          <div class="col-8 offset-2 row">
            <div class="col">
              <input type="submit" class="btn btn-info w-100" value="Create" />
            </div>
            <div class="col">
              <a asp-action="Index" class="btn btn-success w-100">Back to list</a>
            </div>
          </div>
        </div>

      </div>
      <div class="col-4">

      </div>
    </div>

  </div>
</form>
@section Scripts{

  @{
    <partial name="_ValidationScriptsPartial" />
  }

}

CrazyBooks/CrazyBooks/Views/Subject/Index.cshtml
<div class="container p-3 DivBgForm text-light" >
  <div class="row pt-4">
    <div class="col-10">
      <h1 class="text-primary">Book's Subject</h1>
    </div>
    <div class="col-2 text-right">
      <a asp-controller="Subject" asp-action="Create" class="btn btn-success">
        Create New Subject
      </a>
    </div>
  </div>

  <br /><br />
    <table class="table table-bordered border-dark text-light" style="width:100%">
    <thead class="bg-primary">
      <tr>
        <th>
          Subject
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody class="border-dark">
      @foreach (var item in this.ViewBag.MaListe)
      {
        <tr>
          <td width="70%">@item.Name</td>
          <td class="text-center">
            <div class="w-75 btn-group" role="group">
              <a class="btn btn-warning mx-2">
                Edit
              </a>
              <a class="btn btn-danger mx-2">
                Delete
              </a>
            </div>
          </td>
        </tr>
       
      }

    </tbody>
  </table>
</div>